### PR TITLE
Fix: "Failed to create new Configmap ... already exists"

### LINKED ISSUE #217: Operator fails to deploy node sensor reporting that ConfigMap already exists
I am trying to run the node sensor using the operator. I do not use OLM.

Following the instructions, I ran:

`kubectl apply -f https://raw.githubusercontent.com/CrowdStrike/falcon-operator/main/deploy/falcon-operator.yaml`

Followed by

`kubectl create -f https://raw.githubusercontent.com/CrowdStrike/falcon-operator/main/config/samples/falcon_v1alpha1_falconnodesensor.yaml --edit=true` 

and entering my customer details. 

According to the operator logs, it creates a configmap, immediately complains the configmap exists, and refuses to proceed.

```
1.6503031794992795e+09	INFO	controller.falconnodesensor	Configmap was just created. Re-queuing	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "name": "falcon-node-sensor", "namespace": "", "DaemonSet": "/falcon-node-sensor"}
1.650303343339592e+09	INFO	controller.falconnodesensor	reconciling FalconNodeSensor	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "name": "falcon-node-sensor", "namespace": "", "DaemonSet": "/falcon-node-sensor"}
I0418 17:35:44.390364       1 request.go:665] Waited for 1.043420491s due to client-side throttling, not priority and fairness, request: GET:https://10.100.0.1:443/apis/coordination.k8s.io/v1beta1?timeout=32s
1.6503033451699967e+09	ERROR	controller.falconnodesensor	Failed to create new Configmap	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "name": "falcon-node-sensor", "namespace": "", "DaemonSet": "/falcon-node-sensor", "Configmap.Namespace": "falcon-system", "Configmap.Name": "falcon-node-sensor-config", "error": "configmaps \"falcon-node-sensor-config\" already exists"}
github.com/crowdstrike/falcon-operator/controllers/falcon.(*FalconNodeSensorReconciler).Reconcile
```

any idea where I went wrong? The value for FALCONCTL_OPT_CID in the generated configmap appears correct to me.

### PR DESCRIPTION
**Pull request by isimluk**
Fixes #217

Addressing infinite loop with following error:
```
ERROR	controller.falconnodesensor	Failed to create new Configmap	{"reconciler group": "falcon.crowdstrike.com", "reconciler kind": "FalconNodeSensor", "name": "falcon-node-sensor", "namespace": "", "DaemonSet": "/falcon-node-sensor", "Configmap.Namespace": "falcon-system", "Configmap.Name": "falcon-node-sensor-config", "error": "configmaps \"falcon-node-sensor-config\" already exists"}
```

## Description of the problem:

The following events happen in the infinite loop
 - Get() of the config map returns NotFound
 - Create() of the config map returns AlreadyExists

For some reason, the cache of the Get command is never invalidated after
creation. We have seen this issue in EKS, but it may not be isolated to EKS.
We have not been able to reproduce this in house. And the root cause of the
cache not being properly invalidated is not known.

## Description of the solution:

We can easily tell in the code, when this happens and since it is non-fatal for
the purposes of the sensor deployment, we can safely proceed ignoring this
issue. Morever, we can force update the content of a given configmap to calm
down those who would think that it is needed.

### CODE REVIEW

File: main.go [hunk 1]
```diff
@@ -85,6 +85,7 @@ func main() {
 		os.Exit(1)
 	}
 
+	setupLog.Info("setting up a mannager with", "watchNamespace", watchNamespace)
```
Comment (redhatrises) [inline main.go:88]:
```suggestion
	setupLog.Info("setting up manager to watch resources", "watchNamespace", watchNamespace)
```
